static const char *lens_name = "itoh zoom"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 82.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 32.799999; // sensor facing radius in mm
static const float lens_length = 399.554016; // overall lens length in mm
static const float lens_focal_length = 149.673996; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 145.910004; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 26.900000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 296.140015; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.978428; // cosine of the approximate field of view assuming a 35mm image
