static const char *lens_name = "canon zoom"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 38.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 21.000000; // sensor facing radius in mm
static const float lens_length = 237.519974; // overall lens length in mm
static const float lens_focal_length = 54.500000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 119.129997; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 21.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 311.919006; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.954140; // cosine of the approximate field of view assuming a 35mm image
