static const char *lens_name = "double gauss angenieux"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 27.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 17.500000; // sensor facing radius in mm
static const float lens_length = 91.206001; // overall lens length in mm
static const float lens_focal_length = 27.871000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 32.044998; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 12.750000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 82.059998; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.904326; // cosine of the approximate field of view assuming a 35mm image
