static const char *lens_name = "brendel tessar"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 19.200001; // scene facing radius in mm
static const float lens_inner_pupil_radius = 16.500000; // sensor facing radius in mm
static const float lens_length = 119.451004; // overall lens length in mm
static const float lens_focal_length = 79.831001; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 16.059999; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 15.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 42.970001; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.976099; // cosine of the approximate field of view assuming a 35mm image
