static const char *lens_name = "wideangle 1971"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 50.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 30.000000; // sensor facing radius in mm
static const float lens_length = 301.760010; // overall lens length in mm
static const float lens_focal_length = 131.190002; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 128.009995; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 25.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 96.150002; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.976369; // cosine of the approximate field of view assuming a 35mm image
