static const char *lens_name = "double gauss"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 20.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 20.000000; // sensor facing radius in mm
static const float lens_length = 125.580002; // overall lens length in mm
static const float lens_focal_length = 71.000000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 25.889999; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 12.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 33.139999; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.976215; // cosine of the approximate field of view assuming a 35mm image
