static const char *lens_name = "lensbaby"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 24.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 20.000000; // sensor facing radius in mm
static const float lens_length = 123.800003; // overall lens length in mm
static const float lens_focal_length = 65.000000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 58.799999; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 20.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 65.220001; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.981641; // cosine of the approximate field of view assuming a 35mm image
