static const char *lens_name = "fisheye aspherical"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 22.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 12.900000; // sensor facing radius in mm
static const float lens_length = 80.000000; // overall lens length in mm
static const float lens_focal_length = 14.000000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 44.909996; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 6.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 40.820000; // radius of curvature of the outer pupil
static const float lens_field_of_view = -1.000000; // cosine of the approximate field of view assuming a 35mm image
