static const char *lens_name = "petzval"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 11.250000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 6.750000; // sensor facing radius in mm
static const float lens_length = 82.800003; // overall lens length in mm
static const float lens_focal_length = 37.500000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 22.949999; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 7.500000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 39.675003; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.943979; // cosine of the approximate field of view assuming a 35mm image
