static const char *lens_name = "tessar anamorphic"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 40.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 16.500000; // sensor facing radius in mm
static const float lens_length = 195.369995; // overall lens length in mm
static const float lens_focal_length = 90.000000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 81.809998; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 15.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 128.300003; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.987898; // cosine of the approximate field of view assuming a 35mm image
