static const char *lens_name = "petzval kodak"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 11.500000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 7.500000; // sensor facing radius in mm
static const float lens_length = 68.700005; // overall lens length in mm
static const float lens_focal_length = 28.250000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 21.750000; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 9.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 35.485001; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.910063; // cosine of the approximate field of view assuming a 35mm image
