static const char *lens_name = "human eye"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 5.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 5.000000; // sensor facing radius in mm
static const float lens_length = 25.209999; // overall lens length in mm
static const float lens_focal_length = 17.600000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 3.600000; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 3.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 7.800000; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.517864; // cosine of the approximate field of view assuming a 35mm image
