static const char *lens_name = "kreitzer tele"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 35.599998; // scene facing radius in mm
static const float lens_inner_pupil_radius = 16.400000; // sensor facing radius in mm
static const float lens_length = 262.367981; // overall lens length in mm
static const float lens_focal_length = 75.839996; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 157.003998; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 19.200001; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 132.287994; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.998518; // cosine of the approximate field of view assuming a 35mm image
