static const char *lens_name = "double gauss 1930"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 13.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 13.000000; // sensor facing radius in mm
static const float lens_length = 115.919998; // overall lens length in mm
static const float lens_focal_length = 85.000000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 14.630000; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 10.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 22.660000; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.976992; // cosine of the approximate field of view assuming a 35mm image
