static const char *lens_name = "wideangle ii"; // descriptive name of the lens
static const float lens_outer_pupil_radius = 22.000000; // scene facing radius in mm
static const float lens_inner_pupil_radius = 10.000000; // sensor facing radius in mm
static const float lens_length = 121.551003; // overall lens length in mm
static const float lens_focal_length = 37.541000; // approximate lens focal length in mm (BFL)
static const float lens_aperture_pos = 62.269997; // distance aperture -> outer pupil in mm
static const float lens_aperture_housing_radius = 8.000000; // lens housing radius at the aperture
static const float lens_outer_pupil_curvature_radius = 41.021999; // radius of curvature of the outer pupil
static const float lens_field_of_view = 0.188127; // cosine of the approximate field of view assuming a 35mm image
